var sidebar = [
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],
		
	[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

	[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
									],

	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'coffe', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській',text:'orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	]
];

