var sidebar = [
	[[{name: 'cart 1.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.1.1',text:'1.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 1.1.2',text:'1.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 1.1.3',text:'1.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 1.1.4',text:'1.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 1.1.5',text:'1.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 1.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.2.1',text:'1.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.2.2',text:'1.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.2.3',text:'1.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.2.4',text:'1.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.2.5',text:'1.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 1.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.3.1',text:'1.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.3.2',text:'1.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.3.3',text:'1.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.3.4' ,text:'1.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.3.5',text:'1.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 1.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.4.1',text:'1.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.4.2',text:'1.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.4.3',text:'1.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.4.4',text:'1.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.4.5',text:'1.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 1.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.5.1',text:'1.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.5.2',text:'1.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.5.3',text:'1.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.5.4',text:'1.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.5.5',text:'1.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 1.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.6.1',text:'1.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.6.2',text:'1.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.6.3',text:'1.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.6.4',text:'1.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.6.5',text:'1.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 1.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.7.1',text:'1.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.7.2',text:'1.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 1.7.3',text:'1.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 1.7.4',text:'1.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 1.7.5',text:'1.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 1.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 1.8.1',text:'Тиса 1.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 1.8.2',text:'Тиса 1.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 1.8.3',text:'Тиса 1.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 1.8.4',text:'Тиса 1.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 1.8.5',text:'Тиса 1.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 2.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.1.1',text:'2.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 2.1.2',text:'2.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 2.1.3',text:'2.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 2.1.4',text:'2.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 2.1.5',text:'2.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 2.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.2.1',text:'2.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.2.2',text:'2.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.2.3',text:'2.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.2.4',text:'2.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.2.5',text:'2.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 2.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.3.1',text:'2.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.3.2',text:'2.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.3.3',text:'2.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.3.4' ,text:'2.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.3.5',text:'2.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 2.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.4.1',text:'2.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.4.2',text:'2.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.4.3',text:'2.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.4.4',text:'2.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.4.5',text:'2.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 2.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.5.1',text:'2.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.5.2',text:'2.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.5.3',text:'2.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.5.4',text:'2.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.5.5',text:'2.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 2.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.6.1',text:'2.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.6.2',text:'2.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.6.3',text:'2.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.6.4',text:'2.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.6.5',text:'2.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 2.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.7.1',text:'2.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 2.7.2',text:'2.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 2.7.3',text:'2.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 2.7.4',text:'2.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 2.7.5',text:'2.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 2.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 2.8.1',text:'Тиса 2.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 2.8.2',text:'Тиса 2.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 2.8.3',text:'Тиса 2.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 2.8.4',text:'Тиса 2.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 2.8.5',text:'Тиса 2.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 3.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.1.1',text:'3.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 3.1.2',text:'3.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 3.1.3',text:'3.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 3.1.4',text:'3.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 3.1.5',text:'3.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 3.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.2.1',text:'3.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.2.2',text:'3.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.2.3',text:'3.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.2.4',text:'3.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.2.5',text:'3.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 3.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.3.1',text:'3.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.3.2',text:'3.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.3.3',text:'3.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.3.4' ,text:'3.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.3.5',text:'3.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 3.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.4.1',text:'3.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.4.2',text:'3.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.4.3',text:'3.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.4.4',text:'3.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.4.5',text:'3.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 3.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.5.1',text:'3.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.5.2',text:'3.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.5.3',text:'3.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.5.4',text:'3.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.5.5',text:'3.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 3.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.6.1',text:'3.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.6.2',text:'3.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.6.3',text:'3.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.6.4',text:'3.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.6.5',text:'3.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 3.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.7.1',text:'3.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 3.7.2',text:'3.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 3.7.3',text:'3.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 3.7.4',text:'3.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 3.7.5',text:'3.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 3.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 3.8.1',text:'Тиса 3.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 3.8.2',text:'Тиса 3.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 3.8.3',text:'Тиса 3.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 3.8.4',text:'Тиса 3.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 3.8.5',text:'Тиса 3.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 4.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.1.1',text:'4.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 4.1.2',text:'4.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 4.1.3',text:'4.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 4.1.4',text:'4.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 4.1.5',text:'4.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 4.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.2.1',text:'4.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.2.2',text:'4.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.2.3',text:'4.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.2.4',text:'4.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.2.5',text:'4.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 4.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.3.1',text:'4.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.3.2',text:'4.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.3.3',text:'4.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.3.4' ,text:'4.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.3.5',text:'4.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 4.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.4.1',text:'4.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.4.2',text:'4.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.4.3',text:'4.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.4.4',text:'4.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.4.5',text:'4.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 4.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.5.1',text:'4.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.5.2',text:'4.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.5.3',text:'4.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.5.4',text:'4.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.5.5',text:'4.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 4.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.6.1',text:'4.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.6.2',text:'4.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.6.3',text:'4.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.6.4',text:'4.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.6.5',text:'4.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 4.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.7.1',text:'4.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 4.7.2',text:'4.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 4.7.3',text:'4.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 4.7.4',text:'4.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 4.7.5',text:'4.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 4.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 4.8.1',text:'Тиса 4.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 4.8.2',text:'Тиса 4.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 4.8.3',text:'Тиса 4.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 4.8.4',text:'Тиса 4.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 4.8.5',text:'Тиса 4.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 5.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.1.1',text:'5.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 5.1.2',text:'5.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 5.1.3',text:'5.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 5.1.4',text:'5.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 5.1.5',text:'5.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 5.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.2.1',text:'5.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.2.2',text:'5.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.2.3',text:'5.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.2.4',text:'5.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.2.5',text:'5.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 5.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.3.1',text:'5.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.3.2',text:'5.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.3.3',text:'5.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.3.4' ,text:'5.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.3.5',text:'5.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 5.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.4.1',text:'5.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.4.2',text:'5.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.4.3',text:'5.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.4.4',text:'5.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.4.5',text:'5.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 5.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.5.1',text:'5.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.5.2',text:'5.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.5.3',text:'5.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.5.4',text:'5.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.5.5',text:'5.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 5.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.6.1',text:'5.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.6.2',text:'5.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.6.3',text:'5.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.6.4',text:'5.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.6.5',text:'5.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 5.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.7.1',text:'5.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 5.7.2',text:'5.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 5.7.3',text:'5.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 5.7.4',text:'5.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 5.7.5',text:'5.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 5.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 5.8.1',text:'Тиса 5.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 5.8.2',text:'Тиса 5.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 5.8.3',text:'Тиса 5.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 5.8.4',text:'Тиса 5.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 5.8.5',text:'Тиса 5.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 6.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.1.1',text:'6.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 6.1.2',text:'6.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 6.1.3',text:'6.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 6.1.4',text:'6.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 6.1.5',text:'6.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 6.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.2.1',text:'6.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.2.2',text:'6.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.2.3',text:'6.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.2.4',text:'6.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.2.5',text:'6.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 6.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.3.1',text:'6.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.3.2',text:'6.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.3.3',text:'6.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.3.4' ,text:'6.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.3.5',text:'6.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 6.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.4.1',text:'6.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.4.2',text:'6.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.4.3',text:'6.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.4.4',text:'6.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.4.5',text:'6.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 6.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.5.1',text:'6.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.5.2',text:'6.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.5.3',text:'6.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.5.4',text:'6.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.5.5',text:'6.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 6.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.6.1',text:'6.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.6.2',text:'6.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.6.3',text:'6.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.6.4',text:'6.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.6.5',text:'6.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 6.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.7.1',text:'6.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 6.7.2',text:'6.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 6.7.3',text:'6.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 6.7.4',text:'6.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 6.7.5',text:'6.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 6.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 6.8.1',text:'Тиса 6.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 6.8.2',text:'Тиса 6.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 6.8.3',text:'Тиса 6.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 6.8.4',text:'Тиса 6.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 6.8.5',text:'Тиса 6.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 7.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.1.1',text:'7.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 7.1.2',text:'7.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 7.1.3',text:'7.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 7.1.4',text:'7.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 7.1.5',text:'7.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 7.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.2.1',text:'7.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.2.2',text:'7.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.2.3',text:'7.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.2.4',text:'7.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.2.5',text:'7.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 7.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.3.1',text:'7.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.3.2',text:'7.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.3.3',text:'7.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.3.4' ,text:'7.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.3.5',text:'7.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 7.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.4.1',text:'7.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.4.2',text:'7.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.4.3',text:'7.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.4.4',text:'7.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.4.5',text:'7.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 7.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.5.1',text:'7.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.5.2',text:'7.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.5.3',text:'7.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.5.4',text:'7.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.5.5',text:'7.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 7.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.6.1',text:'7.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.6.2',text:'7.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.6.3',text:'7.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.6.4',text:'7.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.6.5',text:'7.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 7.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.7.1',text:'7.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 7.7.2',text:'7.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 7.7.3',text:'7.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 7.7.4',text:'7.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 7.7.5',text:'7.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 7.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 7.8.1',text:'Тиса 7.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 7.8.2',text:'Тиса 7.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 7.8.3',text:'Тиса 7.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 7.8.4',text:'Тиса 7.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 7.8.5',text:'Тиса 7.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 8.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.1.1',text:'8.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 8.1.2',text:'8.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 8.1.3',text:'8.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 8.1.4',text:'8.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 8.1.5',text:'8.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 8.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.2.1',text:'8.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 8.2.2',text:'8.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.2.3',text:'8.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.2.4',text:'8.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.2.5',text:'8.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 8.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.3.1',text:'8.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 8.3.2',text:'8.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.3.3',text:'8.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.3.4' ,text:'8.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.3.5',text:'8.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 8.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.4.1',text:'8.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 8.4.2',text:'8.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.4.3',text:'8.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.4.4',text:'8.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.4.5',text:'8.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 8.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.5.1',text:'8.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 8.5.2',text:'8.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.5.3',text:'8.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.5.4',text:'8.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.5.5',text:'8.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 8.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.6.1',text:'8.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 1.6.2',text:'8.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.6.3',text:'8.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.6.4',text:'8.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.6.5',text:'8.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 8.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.7.1',text:'8.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 8.7.2',text:'8.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 8.7.3',text:'8.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 8.7.4',text:'8.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 8.7.5',text:'8.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 8.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 8.8.1',text:'Тиса 8.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 8.8.2',text:'Тиса 8.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 8.8.3',text:'Тиса 8.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 8.8.4',text:'Тиса 8.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 8.8.5',text:'Тиса 8.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
	[[{name: 'cart 9.1', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.1.1',text:'9.1.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'701'},
		{name: 'Старий Кахеті 9.1.2',text:'9.1.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '702',price:'702'},
		{name: 'Квінт 9.1.3',text:'9.1.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '703',price:'703'},
		{name: 'Оквін 9.1.4',text:'9.1.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '704',price:'704'},
		{name: 'Старовірменській 9.1.5',text:'9.1.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '705',price:'705'},],

		[{name: 'coffe 9.2', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.2.1',text:'9.2.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.2.2',text:'9.2.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.2.3',text:'9.2.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.2.4',text:'9.2.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.2.5',text:'9.2.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'beer 9.3', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.3.1',text:'9.3.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.3.2',text:'9.3.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.3.3',text:'9.3.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.3.4' ,text:'9.3.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.3.5',text:'9.3.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tincture 9.4', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.4.1',text:'9.4.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.4.2',text:'9.4.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.4.3',text:'9.4.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.4.4',text:'9.4.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.4.5',text:'9.4.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Vodka 9.5', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.5.1',text:'9.5.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.5.2',text:'9.5.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.5.3',text:'9.5.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.5.4',text:'9.5.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.5.5',text:'9.5.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Cognac 9.6', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.6.1',text:'9.6.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.6.2',text:'9.6.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.6.3',text:'9.6.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.6.4',text:'9.6.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.6.5',text:'9.6.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'BourgeoisDrinks 9.7', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.7.1',text:'9.7.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті 9.7.2',text:'9.7.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт 9.7.3',text:'9.7.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін 9.7.4',text:'9.7.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській 9.7.5',text:'9.7.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},],

		[{name: 'Tinctures 9.8', amount : 'Кількість', amountP : 'Ціна, грн',
			amountSize : '50мл', size : '1 л'},
		{name: 'Тиса 9.8.1',text:'Тиса 9.8.1 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '100/70/50',price:'700'},
		{name: 'Старий Кахеті Тиса 9.8.2',text:'Тиса 9.8.2 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Квінт Тиса 9.8.3',text:'Тиса 9.8.3 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Оквін Тиса 9.8.4',text:'Тиса 9.8.4 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},
		{name: 'Старовірменській Тиса 9.8.5',text:'Тиса 9.8.5 orem ipsum dolor sit amet, consectetur adipiscing elit. (Fusce sed placerat tortor. Aliquam ultricies ut felis sed porta. Donec vel augue sed ligula ultrices congue',
		size: '700',price:'700'},]
	],
];

